---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: automerge-pipeline-pullrequest-binding
spec:
  params:
  - name: pullrequesturl
    value: $(body.pull_request.html_url)
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)
  - name: event-type
    value: $(header.X-GitHub-Event)
  - name: branch-name
    value: $(body.pull_request.head.ref)
  - name: commit-name
    value: YOUR-GIT-USER-NAME
  - name: commit-email
    value: YOUR-GIT-EMAIL
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: automerge-pipeline-push-binding
spec:
  params:
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)
  - name: event-type
    value: $(header.X-GitHub-Event)
  - name: branch-name
    value: $(body.ref)


