apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: automerge-pipeline
spec:
  params:
  - name: github-secret
    type: string
  - name: event-type
    type: string
  - name: branch-name
    type: string
  - name: pull-request-url
    type: string
  - name: commit-name
    type: string
  - name: commit-email
    type: string
  resources: 
  - name: source-repo
    type: git
  tasks:
  - name: test-and-automerge
    taskRef:
      name: automerge-task
    resources:
      inputs:
      - name: git-source
        resource: source-repo
    params:
    - name: github-secret
      value: $(params.github-secret)
    - name: event-type
      value: $(params.event-type)
    - name: branch-name
      value: $(params.branch-name)
    - name: pull-request-url
      value: $(params.pull-request-url)
    - name: commit-name
      value: $(params.commit-name)
    - name: commit-email
      value: $(params.commit-email)
