apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: automerge-task
spec:
  params:
  - name: commit-name
    type: string
    description: GitHub name to author the commit with
  - name: commit-email
    type: string
    description: GitHub email to author the commit with
  - name: github-secret
    type: string
    description: Name of the secret containing an access token for Github. Expects Tekton format, 'username' and 'password' keys.
  inputs:
    resources:
      - name: git-source
        type: git
      - name: pull-request
        type: pullRequest
  steps:
  - name: check-yaml
    image: YOUR_DOCKER_HUB_ID/hub-test
    script: |
      #!/bin/bash
      kubectl apply -k git-source/environments/dev/env --dry-run=client
  - name: merge-pr
    image: YOUR_DOCKER_HUB_ID/hub-test
    script: |
      #!/bin/bash -x
      fullPRLink=$(yq r pull-request/pr.json 'Link')
      prURL=${fullPRLink%.diff}

      git config --global user.name $(params.commit-name)
      git config --global user.email $(params.commit-email)
      cd git-source
      hub merge $prURL
      git push -u origin master

      # Pushing the change will merge the PR. Delete its branch to tidy up. 
      prBranch=$(yq r /workspace/pull-request/pr.json 'Head.Ref')
      git push origin --delete $prBranch

    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.github-secret)
          key: password