apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: gitops-repo
spec:
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/YOUR_GITHUB_ID/gitops-example-dev
  - name: refspec
    value: refs/heads/*:refs/heads/*
  - name: depth
    value: "0"
  type: git